pipeline:
  name: Build app-demo-argocd
  identifier: Build_app_demo_argocd_1785433837323
  projectIdentifier: CaPer_CI_CD
  orgIdentifier: Jorge_playground
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Bienvenido a la Capacitación Personal de CI/CD"
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Imagen1
                  identifier: Imagen1
                  spec:
                    repo: jiggdemocaper
                    tags:
                      - latest
                    caching: true
                    registryRef: account.kcd_docker_registry
              - step:
                  type: GitClone
                  name: clonar codigo
                  identifier: clonar_codigo
                  spec:
                    connectorRef: jigg_github
                    build:
                      type: branch
                      spec:
                        branch: main
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.GitHub_David
        repoName: app-demo-argocd
        build: <+input>
